### ISSUE TITLE
InfluxDB export in 2.8.1 is broken

### ISSUE THREAD

**Issue by lgromb** [nicolargo/glances#1026]
Hi,

Just tried to export data to InfluxDB with 

 `glances --export-influxdb --quiet -d --disable-now` (v2.8.1)

Throws this 

` File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_export.py", line 153, in update
    all_stats = stats.getAllExportsAsDict(plugin_list=self.plugins_to_export())
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 209, in getAllExportsAsDict
    return {p: self._plugins[p].get_export() for p in plugin_list}
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 209, in <dictcomp>
    return {p: self._plugins[p].get_export() for p in plugin_list}
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_uptime.py", line 62, in get_export
    return {'seconds': self.uptime.second}
AttributeError: 'datetime.timedelta' object has no attribute 'second'
`

It works with 2.8.

**Comment by nicolargo** [comment]
Corrected.

Version 2.8.2 will be available soon.
