### ISSUE TITLE
Cannot restart glances with --export influxdb after update to 3.1.1 

### ISSUE THREAD

**Issue by bzazzera** [nicolargo/glances#1530]
Hi,
I cannot restart glances with --export influxdb after update to 3.1.1.

See error below 
# /usr/local/bin/glances --quiet --config /etc/glances/glances.conf --export influxdb
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 49, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 47, in __init__
    self.load_modules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 101, in load_modules
    self.load_exports(args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 179, in load_exports
    config=self.config)
  File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_influxdb.py", line 60, in __init__
    self.client = self.init()
  File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_influxdb.py", line 70, in init
    ssl=(self.protocol.lower() == 'https'),
AttributeError: 'NoneType' object has no attribute 'lower'

# glances -V                                                                                                                                                                                               
Glances v3.1.1 with psutil v5.6.3

This problem occurs on two machines under Ubuntu 18.04 and Debian 9.8

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

Can anyone help me ? How roll back to 3.1.0 ?

Many thanks in advance.

Bruno.

**Comment by bzazzera** [comment]
Rolled back to 3.1.0 and everything's back to normal on both servers ! 

A bug with Influxdb on 3.1.1 ?

**Comment by nicolargo** [comment]
As a workaround for the version 3.1.1, please add the following option in the Glances conf file:

```
[influxdb]
...
protocol=http
...
```

**Comment by nicolargo** [comment]
Patch ok on the DEVELOP branch.

**Comment by bzazzera** [comment]
I confirm, after added :
[influxdb] 
protocol=http
in glances.conf
it works now with 3.1.1 but just a small error occurs in syslog: 
glances: Error while initializing the quicklook plugin (encode() argument 1 must be string, not None)
Many Thanks Nicolas
