### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by dkleva** [nicolargo/glances#1501]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description
curl -L https://bit.ly/glances | /bin/bash
For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 948kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-19.1.1
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

#### Versions

* Glances & psutil (glances -V):
* Operating System (lsb_release -a):
Debian GNU/Linux 9

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by martinburger** [comment]
I run into the same issue on Ubuntu 16.04.6 LTS. However, the second call of `curl -L https://bit.ly/glances | /bin/bash` successfully installed Glances.

**Comment by victorromeo** [comment]
> I run into the same issue on Ubuntu 16.04.6 LTS. However, the second call of `curl -L https://bit.ly/glances | /bin/bash` successfully installed Glances.

Doesn't work on 18.04 LTS

**Comment by RazCrimson** [comment]
Closing as stale issue
