### ISSUE TITLE
Glances is not compatible with the new Docker API 2.0 (Docker 1.13)

### ISSUE THREAD

**Issue by bacondropped** [nicolargo/glances#1000]
#### Description

After updating Docker client API to 2.0, `glances` reliably crashes with or without
`--disable-docker` with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_plugin.py", line 734, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_docker.py", line 153, in update
    self.docker_client = self.connect()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_docker.py", line 98, in connect
    ret = docker.Client(base_url='unix://var/run/docker.sock')
AttributeError: module 'docker' has no attribute 'Client'
```

Apparently, it happens due to a breaking change in the Python API (`docker` now has the old-style `APIClient` and newer `DockerClient`). If you try to run something like
```
import docker
c = docker.DockerClient()
c.containers()
```
.., you'll get an error message that sort of explains what to do:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/docker/models/resource.py", line 67, in __call__
    .format(self.__class__.__name__))
TypeError: 'ContainerCollection' object is not callable. You might be trying to use the old (pre-2.0) API - use docker.APIClient if so.
```

#### Versions

* Glances (glances -V): `Glances v2.7.1 with psutil v5.0.1`
* Operating System (lsb_release -a):
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0-dev
Codename:	Gellivara
```

* `docker info` (truncated):

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Server Version: 1.12.6
Storage Driver: devicemapper
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
OSType: linux
Architecture: x86_64
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
```

* `pip list | grep docker`:
```
docker (2.0.1)
docker-compose (1.10.0)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

#### My hotfix

```patch
diff --git a/glances/plugins/glances_docker.py b/glances/plugins/glances_docker.py
index d0df668..5827d0e 100644
--- a/glances/plugins/glances_docker.py
+++ b/glances/plugins/glances_docker.py
@@ -93,12 +93,18 @@ class Plugin(GlancesPlugin):
     def connect(self, version=None):
         """Connect to the Docker server."""
         # Init connection to the Docker API
+
+        if hasattr(docker, 'APIClient'):
+            init_docker = docker.APIClient
+        else:
+            init_docker = docker.Client
+
         try:
             if version is None:
-                ret = docker.Client(base_url='unix://var/run/docker.sock')
+                ret = init_docker(base_url='unix://var/run/docker.sock')
             else:
-                ret = docker.Client(base_url='unix://var/run/docker.sock',
-                                    version=version)
+                ret = init_docker(base_url='unix://var/run/docker.sock',
+                                  version=version)
         except NameError:
             # docker lib not found
             return None
```

(not tested on the older Docker API, but works for me).

**Comment by nicolargo** [comment]
Thanks @bacondropped for this 1000 issue ;)

Your patch also work for older Docker API. Patch will be integrated to the next 2.8 Glances release.

**Comment by nicolargo** [comment]
@bacondropped Pushed on DELOP branch, can you test it ?

**Comment by bacondropped** [comment]
@138cb2d seems to work well on my setup.

**Comment by nicolargo** [comment]
Thanks for all @bacondropped  !
